---
- name: Ensure Prometheus group exists
  ansible.builtin.group:
    name: "{{ prometheus_group }}"
    state: present

- name: Ensure Prometheus user exists
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false
    state: present

- name: Create Prometheus directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0755"
  loop:
    - "{{ prometheus_data_dir }}"
    - "{{ prometheus_config_dir }}"

- name: Download Prometheus
  ansible.builtin.get_url:
    url: "{{ prometheus_download_url }}"
    dest: "/tmp/prometheus.tar.gz"
    mode: "0644"

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "/tmp"
    remote_src: true

- name: Copy Prometheus binaries
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
    dest: "{{ prometheus_install_dir }}/prometheus"
    owner: root
    group: root
    mode: "0755"
    remote_src: true

- name: Copy Prometheus config
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/promtool"
    dest: "{{ prometheus_install_dir }}/promtool"
    owner: root
    group: root
    mode: "0755"
    remote_src: true

- name: Copy Prometheus default config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0644"

- name: Create Prometheus service
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/{{ prometheus_service_name }}.service
    mode: "0644"

- name: Notify systemd to reload
  ansible.builtin.systemd:
    daemon_reload: true
  notify: Restart Prometheus

- name: Enable and start Prometheus service
  ansible.builtin.systemd:
    name: "{{ prometheus_service_name }}"
    enabled: true
    state: started
