myhosts:
  hosts:
    vagrant:
      ansible_host: 192.168.60.60
      ansible_ssh_private_key_file: /mnt/Code/Jackson/docker-vm/ssh/vagrant
      ansible_user: vagrant
      ansible_password: vagrant
