all:
  hosts:
    prometheus:
      ansible_host: 192.168.60.60
      ansible_user: vagrant
      ansible_ssh_pass: vagrant
      ansible_ssh_private_key_file: ./ssh/vagrant_ed25519
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    webserver:
      ansible_host: 192.168.60.61
      ansible_user: vagrant
      ansible_ssh_pass: vagrant
      ansible_ssh_private_key_file: ./ssh/vagrant_ed25519
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  vars:
    ansible_python_interpreter: /usr/bin/python3
