---
- name: Ping vagrant hosts
  hosts:
    - prometheus-server
    - webserver
  tasks:
    - name: Ping vagrant hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world
