---
- name: Install Git on myhosts
  hosts: myhosts
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: present
