---
- name: Install Prometheus on Servers
  hosts: prometheus
  become: true
  roles:
    - role: prometheus

- name: Install Grafana on Debian Servers
  hosts: prometheus
  become: true
  roles:
    - role: grafana

- name: Install Prometheus Node Exporter on Servers
  hosts: all
  become: true
  roles:
    - role: prometheus_exporter
