---
- name: Ensure prometheus user exists
  ansible.builtin.user:
    name: "{{ prometheus_exporter_exporter_user }}"
    state: present
    system: true
    shell: /usr/sbin/nologin

- name: Download Node Exporter
  ansible.builtin.get_url:
    url: "{{ prometheus_exporter_node_exporter_download_url }}"
    dest: "/tmp/node_exporter-{{ prometheus_exporter_node_exporter_version }}.tar.gz"
    mode: "0644"

- name: Extract Node Exporter
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter-{{ prometheus_exporter_node_exporter_version }}.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: true

- name: Move Node Exporter binaries
  ansible.builtin.command:
    cmd: mv /usr/local/bin/node_exporter-{{ prometheus_exporter_node_exporter_version }}.linux-amd64/node_exporter /usr/local/bin/node_exporter
  args:
    creates: "/usr/local/bin/node_exporter"
  become: true

- name: Set permissions for Node Exporter binary
  ansible.builtin.file:
    path: "/usr/local/bin/node_exporter"
    owner: "{{ prometheus_exporter_exporter_user }}"
    group: "{{ prometheus_exporter_exporter_user }}"
    mode: "0755"

- name: Create Node Exporter systemd service file
  ansible.builtin.template:
    src: prometheus-node-exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: "0644"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Ensure Node Exporter service is started and enabled
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: true
